[workspace]
resolver = "2"
members = [
    "cs2-schema/declaration",
    "cs2-schema/cutl",
    "cs2-schema/generated",
    "kinterface",
    "controller",
    "cs2",
    "overlay",
]
exclude = [
    "kernel/driver"
]

[profile.dev]
incremental = true

[profile.release]
panic = "abort"
lto = true