[workspace]
resolver = "2"
members = [
    "kinterface",
    "controller",
    "cs2-schema",
    "cs2",
    "overlay",
]

[profile.dev]
incremental = true

[profile.release]
panic = "abort"
lto = true