[package]
name = "cs2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
obfstr = "0.4.3"
kinterface = { path = "../kinterface"}
log = "0.4.19"
cs2-schema = { path = "../schema" } 
serde_json = "1.0.104"
nalgebra = "0.32.3"
