[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
valthrun-kinterface = { path = "../kinterface"}
cs2-schema = { path = "../schema" } 
log = "0.4.19"
env_logger = "0.10.0"
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
imgui = "0.11"
imgui-winit-support = "0.11.0" 
copypasta = "0.8.2"
winit = "0.28.6"
glium = "0.32.1"
imgui-glium-renderer = "0.11.0" 
windows = { version = "0.48.0", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_Graphics_Dwm", "Win32_Graphics_Gdi", "Win32_UI_Input_KeyboardAndMouse"] }
obfstr = "0.4.3"
nalgebra = "0.32.3"
mint = "0.5.9"
