name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use rust nightly
      run: rustup update nightly && rustup default nightly
    - name: Check fmt
      run: rustup component add rustfmt && cargo fmt --check
    - name: Build
      run: cargo build --verbose
    # Right now there are no tests specified
    # - name: Run tests
    #   run: cargo test --verbose
